### ISSUE TITLE
Bottom few pixels blurring

### ISSUE THREAD

**Issue by hsdk123** [phoboslab/pl_mpeg#47]
Hi, thank you for creating a fantastic library.
I'm currently using this inside my engine, and lately noticed that the bottom few pixels are blurring.
Any thoughts?

![image](https://github.com/user-attachments/assets/74120db3-7b6e-48e7-9e2b-e663d2808d7f)

**Comment by phoboslab** [comment]
That looks like it's caused by incorrect handling of video sizes that are not a multiple of 16.

The internal YUV buffers are always created with a width and height rounded up to the next multiple of 16 . E.g. for a video that has a display height of 20 pixels, the Y plane will have a height 32 pixels.

Have a look at the documentation for `plm_frame_t` and `plm_plane_t` in [pl_mpeg.h](https://github.com/phoboslab/pl_mpeg/blob/master/pl_mpeg.h#L182-L208)
-  `frame->height` should be the desired display size (for the example: 20 pixels)
-  `frame->y.height` is the actual buffer size (for the example: 32 pixels).

That means you have to crop the Y, U and V planes before output - or (if you can) ensure that the input video has a size that is a multiple of 16.

I'm not entirely sure if the dimensions in `pl_frame_t` and `pl_plane_t` are correct; there might be bug somewhere and I think the pl_mpeg_player doesn't handle this correctly either.

Could you maybe provide a short sample (1sec) of the video that exhibits this problem?

**Comment by hsdk123** [comment]
@phoboslab thank you for the fast reply!
I indeed do see that 

- `frame->height` is 1080
- `frame->y.height` is 1088

When you say `crop`, does that mean I need to discard the top or bottom 8 extra pixels?
Here's the full video:

https://drive.google.com/file/d/1ci9Hz_OKuCjjBlVHF9jET_v6UTjlyD5e/view?usp=sharing

**Comment by phoboslab** [comment]
You need to crop out the bottom and right pixels.

![mpeg1-crop](https://github.com/user-attachments/assets/91ce69c9-18bf-40bf-b5d2-c7a9c5bf8e1d)

Above commit fixes the display size in pl_mpeg_player_gl. Thanks for the sample video!

**Comment by hsdk123** [comment]
Thank you
